language: python
python:
  - '3.6'
branches:
  only:
  - fix-travis
services:
  - postgresql
dist:
  - xenial
sudo:
  - required
before_install:
  - sudo apt-get purge python-openssl
  - sudo apt-get install libffi-dev libyaml-dev python-yaml libgnutls28-dev
  - sudo pip install pyopenssl
  - sudo pip install --upgrade pip 
  - psql postgres -c "CREATE USER owtf_db_user WITH PASSWORD 'jgZKW33Q+HZk8rqylZxaPg1lbuNGHJhgzsq3gBKV32g=';"
  - psql postgres -c "CREATE DATABASE owtf_db WITH OWNER owtf_db_user ENCODING 'utf-8' TEMPLATE template0;"
install:
  - pip install -r requirements/base.txt
  - echo '\n\n' | python setup.py develop
before_script:
  - pip install mock pyHamcrest
  - cp -f ./tests/fixtures/profiles/plugin_web/groups.cfg ~/.owtf/conf/profiles/plugin_web/groups.cfg
  - cp -f ./tests/fixtures/profiles/plugin_net/groups.cfg ~/.owtf/conf/profiles/plugin_net/groups.cfg
  - cp -f ./tests/fixtures/profiles/plugin_aux/groups.cfg ~/.owtf/conf/profiles/plugin_aux/groups.cfg
  - git config --global user.email "tasty@mac.test"
  - git config --global user.name "Tasty Test"
  - "./tests/fixtures/skipfish.sh"
script:
  - python -m unittest tests.functional.cli.test_empty_run
  #- python -m unittest tests.functional.cli.test_except
  - python -m unittest tests.functional.cli.test_list_plugins
  - python -m unittest tests.functional.cli.test_nowebui
  #- python -m unittest tests.functional.cli.test_only
  #- python -m unittest tests.functional.cli.test_scope
  #- python -m unittest tests.functional.cli.test_type
  - python -m unittest tests.functional.plugins.web
notifications:
  email: false
